# -*- coding: utf-8 -*-
"""network_usecase.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F_3oFO3cWHpghhZLPtVJc-yjN8Xxw7gX
"""

import torch
from PIL import Image
from torchvision import transforms
import numpy as np
import pandas as pd

resnet_transforms = transforms.Compose([
        transforms.Resize(256),
        transforms.CenterCrop(224),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    ])

! wget "https://getfile.dokpub.com/yandex/get/https://yadi.sk/d/pbVsNO4_OvzPag" -O mushroom_database.csv

! wget "https://getfile.dokpub.com/yandex/get/https://yadi.sk/d/L1vdaKCEG2ZU-w" -O mushroom_model.pt

model_new = torch.load('mushroom_model.pt')

img_test = Image.open("/content/muhomor.jpg")
img_tensor = resnet_transforms(img_test)

img_tensor = img_tensor.view(1, 3, 224, 224)

output = model_new(img_tensor)

prediction_new = int(torch.max(output.data, 1)[1].numpy())
print(prediction_new)

mtd = pd.read_csv('mushroom_database.csv')

mtd.head()

print(mtd['mushroom'].values[prediction_new])
print(mtd['description'].values[prediction_new])
print(mtd['usefulness'].values[prediction_new])
print(mtd['fact'].values[prediction_new])
print(mtd['recipe'].values[prediction_new])

pd.__version__